// Mutations
export const MUTATE_LAST_MESSAGES = 'MUTATE_LAST_MESSAGES';
export const MUTATE_MESSAGES = 'MUTATE_MESSAGES';
export const NEXT_MESSAGE = 'NEXT_MESSAGE';
export const TOGGLE_FOOTER_VISIBILTY = 'TOGGLE_FOOTER_VISIBILTY';

// Actions
export const POST_MESSAGE = 'POST_MESSAGE';

// Getters
export const CURRENT_MESSAGE = 'CURRENT_MESSAGE';
export const IS_CURRENT_MESSAGE_THE_LAST_ONE = 'IS_CURRENT_MESSAGE_THE_LAST_ONE';
export const CURRENT_REPLY_FORM = 'CURRENT_REPLY_FORM';