// Mutations
export const MUTATE_ANSWERS = 'MUTATE_ANSWERS';
export const MUTATE_ANSWERS_HISTORY = 'MUTATE_ANSWERS_HISTORY';
export const MUTATE_NEXT_ANSWER = 'MUTATE_NEXT_ANSWER';
export const MUTATE_LAST_MESSAGES = 'MUTATE_LAST_MESSAGES';
export const MUTATE_MESSAGES = 'MUTATE_MESSAGES';
export const MUTATE_NEXT_MESSAGE = 'MUTATE_NEXT_MESSAGE';
export const MUTATE_TOGGLE_FOOTER_VISIBILTY = 'MUTATE_TOGGLE_FOOTER_VISIBILTY';
export const MUTATE_NAME_INITIAL = 'MUTATE_NAME_INITIAL';
export const MUTATE_FINISH = 'MUTATE_FINISH';

// Actions
export const POST_MESSAGE = 'POST_MESSAGE';
export const POST_ANSWER = 'POST_ANSWER';
export const POST_FINISH = 'POST_FINISH';

// Getters
export const CURRENT_MESSAGE = 'CURRENT_MESSAGE';
export const CURRENT_ANSWER = 'CURRENT_ANSWER';
export const CURRENT_REPLY_FORM = 'CURRENT_REPLY_FORM';
export const IS_CURRENT_MESSAGE_THE_LAST_ONE = 'IS_CURRENT_MESSAGE_THE_LAST_ONE';
export const CURRENT_ANSWER_PAYLOAD = 'CURRENT_ANSWER_PAYLOAD';
